version: "3.8"

services:
  datadog-agent:
    image: datadog/agent:latest
    container_name: datadog-agent
    environment:
      - DD_API_KEY=${DD_API_KEY}
      - DD_SITE=us5.datadoghq.com
      - DD_LOGS_ENABLED=true
      - DD_APM_ENABLED=true
      - DD_PROCESS_AGENT_ENABLED=true
      - DD_LOGS_CONFIG_CONTAINER_COLLECT_ALL=true
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - /proc:/host/proc:ro
      - /sys/fs/cgroup:/host/sys/fs/cgroup:ro
    restart: unless-stopped

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      - DD_SERVICE=frontend-ivanildobarauna-dev
      - DD_ENV=production
      - DD_VERSION=1.0.0
      - DD_TRACE_SAMPLE_RATE=1.0
      - DD_AGENT_HOST=datadog-agent
      - DD_PROCESS_AGENT_ENABLED=true
      - DD_TAGS=app:portfolio,tech:nextjs,role:frontend
    labels:
      com.datadoghq.ad.logs: '[{"source": "nodejs", "service": "frontend-ivanildobarauna-dev"}]'
      com.datadoghq.tags.env: "production"
      com.datadoghq.tags.service: "frontend-ivanildobarauna-dev"
      com.datadoghq.tags.tech: "nextjs"
      com.datadoghq.tags.app: "portfolio"
      com.datadoghq.tags.role: "frontend"
    depends_on:
      - backend
    restart: unless-stopped

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "8090:8090"
    environment:
      - DD_SERVICE=api-ivanildobarauna-dev
      - DD_ENV=production
      - DD_VERSION=1.0.0
      - DD_TRACE_SAMPLE_RATE=1.0
      - DD_AGENT_HOST=datadog-agent
      - DD_PROCESS_AGENT_ENABLED=true
      - DD_TAGS=app:portfolio,tech:python,role:backend
    labels:
      com.datadoghq.ad.logs: '[{"source": "python", "service": "api-ivanildobarauna-dev"}]'
      com.datadoghq.tags.env: "production"
      com.datadoghq.tags.service: "api-ivanildobarauna-dev"
      com.datadoghq.tags.tech: "python"
      com.datadoghq.tags.app: "portfolio"
      com.datadoghq.tags.role: "backend"
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8090/api/v1/ping"]
      interval: 300s
      timeout: 10s
      retries: 3
      start_period: 40s
