version: '3.8'

services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      - NEXT_PUBLIC_BACKEND_URL=http://backend:8090
    depends_on:
      - backend

  backend:
    build:
      context: ../api.ivanildobarauna.dev
      dockerfile: Dockerfile
    ports:
      - "8090:8090"