services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      - NEXT_PUBLIC_BACKEND_URL=http://backend:8090
    depends_on:
      - backend

  backend:
    build:
      context: ../api.ivanildobarauna.dev
      dockerfile: Dockerfile
    ports:
      - "8090:8090"

  # web:
  #   build:
  #     context: .
  #     dockerfile: Dockerfile.new
  #   ports:
  #     - "3000:3000"
  #   environment:
  #     - NODE_ENV=production
  #     - APP_URL=http://localhost:8080
  #   healthcheck:
  #     test: ["CMD", "./scripts/healthcheck.sh"]
  #     interval: 30s
  #     timeout: 30s
  #     retries: 3
  #     start_period: 5s