services:
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: portfolio-frontend
    ports:
      - "8080:8080"
    environment:
      - DD_SERVICE=ivanildobarauna.dev
      - DD_ENV=local
      - DD_VERSION=1.0.0
      - DD_TRACE_SAMPLE_RATE=1.0
      - DD_AGENT_HOST=host.docker.internal
      - DD_PROCESS_AGENT_ENABLED=true
      - DD_TAGS="app:portfolio,tech:nextjs,role:frontend"
    labels:
      com.datadoghq.ad.logs: '[{"source": "nodejs", "service": "ivanildobarauna.dev"}]'
      tags.env: "local"
      tags.service: "ivanildobarauna.dev"
      tags.tech: "nextjs"
      tags.app: "portfolio"
      tags.role: "frontend"
    depends_on:
      - backend
    restart: unless-stopped

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: portfolio-backend
    ports:
      - "8090:8090"
    environment:
      - DD_SERVICE=api.ivanildobarauna.dev
      - DD_ENV=local
      - DD_VERSION=1.0.0
      - DD_TRACE_SAMPLE_RATE=1.0
      - DD_AGENT_HOST=host.docker.internal
      - DD_PROCESS_AGENT_ENABLED=true
      - DD_TAGS="app:portfolio,tech:python,role:backend"
      - DD_RUNTIME_METRICS_ENABLED=true
      - POSTGRES_HOST=192.168.15.44
      - POSTGRES_PORT=5432
      - POSTGRES_USER=backend
      - POSTGRES_PASSWORD=backend
      - POSTGRES_DB=portfolio
    labels:
      com.datadoghq.ad.logs: '[{"source": "python", "service": "api.ivanildobarauna.dev"}]'
      tags.env: "local"
      tags.service: "api.ivanildobarauna.dev"
      tags.tech: "python"
      tags.app: "portfolio"
      tags.role: "backend"
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8090/api/v1/ping"]
      interval: 300s
      timeout: 10s
      retries: 3
      start_period: 40s
