-- Script SQL para inserir experiências profissionais
INSERT INTO experiences (position, period, start_date, company, location, website, logo, actual_job, description, skills, active)
VALUES
    ('Engenheiro de Dados Senior', 'outubro de 2023 - atual', '2023-10-01', 'Mercado Livre', 'São Paulo, Brasil', 'https://www.mercadolivre.com.br', '/images/empresas/mercadolivre.png', TRUE, 'Desenvolvimento de soluções de observabilidade de negócio entre microsserviços. Trabalho com tecnologias como Apache Beam, Google Cloud Platform, e Python', 'BigQuery;Python;Flask;Docker;Microservices;Observability', TRUE),
    
    ('Senior Data Analyst', 'setembro de 2023 - dezembro de 2023', '2023-09-01', 'C6 Bank', 'São Paulo, Brasil', 'https://www.c6bank.com.br', '/images/empresas/c6bank.png', FALSE, 'Responsável por garantir a execução de pipelines e fornecimento de dados para Investimentos, Core Banking e outros assuntos de Corporate Banking. Desenvolvimento de processos de Data Quality. Suporte no desenvolvimento da plataforma de dados do banco', 'SQL;BigQuery;Python;Airflow;DataFlow;Looker Studio', TRUE),
    
    ('Data Analyst', 'janeiro de 2023 - setembro de 2023', '2023-01-01', 'C6 Bank', 'São Paulo, Brasil', 'https://www.c6bank.com.br', '/images/empresas/c6bank.png', FALSE, 'Mapeamento, definição e planejamento de entrada/manutenção de pipelines de Dados no Data Lake. Estruturação e disponibilização de Data Marts e/ou Data Warehouses para as demais áreas do banco. Foco em otimização de custo e performance dos pipelines produtivos', 'SQL;BigQuery;Python;Airflow;DataFlow;Looker Studio', TRUE),
    
    ('Business Intelligence Analyst', 'fevereiro de 2022 - dezembro de 2022', '2022-02-01', 'C6 Bank', 'São Paulo, Brasil', 'https://www.c6bank.com.br', '/images/empresas/c6bank.png', FALSE, 'Desenvolvimento de solução de ETL auto orquestrada para análise de grandes volumes de dados. Foco em redução de custo e criação de Data Mart para área de negócio. Implementação de processos automatizados de transformação de dados', 'SQL;BigQuery;Power BI;Looker Studio', TRUE),
    
    ('Analista de Business Intelligence', 'setembro de 2020 - fevereiro de 2022', '2020-09-01', 'Embracon Administradora de Consórcio Ltda', 'Santana de Parnaíba, São Paulo, Brasil', 'https://www.embracon.com.br', '/images/empresas/embracon.png', FALSE, 'Criação de indicadores de performance de negócio para suporte à tomada de decisão. Desenvolvimento de dashboards e relatórios para acompanhamento de resultados. Automatização de processos de ETL para carga de dados', 'SQL;Power BI;PL/SQL;MSSQL;SSIS;SSRS;Pentaho Data Integration', TRUE),
    
    ('Analista de Aplicações Digitais PL', 'dezembro de 2019 - setembro de 2020', '2019-12-01', 'Embracon Administradora de Consórcio Ltda', 'Santana de Parnaíba, São Paulo, Brasil', 'https://www.embracon.com.br', '/images/empresas/embracon.png', FALSE, 'Construção de Indicadores para tomada de decisão estratégica. Desenvolvimento de análises descritivas e preditivas. Suporte à decisão através de análise de dados', 'SQL;MSSQL', TRUE),
    
    ('Analista de Aplicações Digitais Jr', 'março de 2019 - dezembro de 2019', '2019-03-01', 'Embracon Administradora de Consórcio Ltda', 'Santana de Parnaíba, São Paulo, Brasil', 'https://www.embracon.com.br', '/images/empresas/embracon.png', FALSE, 'Construção de Indicadores para tomada de decisão estratégica. Foco em análise de dados para área comercial. Desenvolvimento de relatórios e dashboards', 'Excel;Power BI;VBA;DAX;M Language', TRUE),
    
    ('Analista de MIS', 'março de 2015 - abril de 2017', '2015-03-01', 'Sitel Brasil | Foundever', 'São Paulo, Brasil', NULL, NULL, FALSE, 'Desenvolvimento de Relatórios em MS-Excel com base nos dados do Salesforce. Automatização de processos manuais com VBA. Desenvolvimento de Dashboards com MS-Excel', 'Excel;VBA', TRUE),
    
    ('Professor de música', 'junho de 2014 - dezembro de 2014', '2014-06-01', 'Colégio e Curso Objetivo', 'São Paulo, Brasil', NULL, NULL, FALSE, 'Filial: ESCOLA DE INTEGRACAO E APRENDIZAGEM CRESCER LTDA. Atribuição: Ensino de teoria musical focada em ensino infantil', 'Ensino de teoria musical para crianças', TRUE),
    
    ('Técnico de suporte em TI', 'janeiro de 2013 - julho de 2013', '2013-01-01', 'Supermercados Rod & Raf', 'São Paulo e Região, Brasil', NULL, NULL, FALSE, 'Manutenção de Computadores. CFTV. Cabeamento estruturado de Redes. Manutenção supervisionada de servidores on premise', 'Linux;Redes;Oracle;PABX;Infraestrutura', TRUE),
    
    ('Técnico de suporte de redes', 'junho de 2012 - dezembro de 2012', '2012-06-01', 'Wave Internet', 'São Paulo, Brasil', NULL, NULL, FALSE, 'Manutenção interna e externa de rádios transmissores e receptores de internet. Acompanhamento de saúde do ambiente com Microtik Router. Apoio na instalação de sistemas operacionais nos servidores centrais', 'Redes;Linux;Microtik;Ubiquiti Routers', TRUE),
    
    ('Jovem aprendiz', 'fevereiro de 2012 - abril de 2012', '2012-02-01', 'Horus Tech Informatica', 'São Paulo, Brasil', NULL, NULL, FALSE, 'Suporte e manutenção de computadores', 'Windows;Redes;MacOS;Linux;Hardware', TRUE),
    
    ('Analista Administrativo', 'dezembro de 2018 - março de 2019', '2018-12-01', 'Embracon Administradora de Consórcio Ltda', 'São Paulo, Brasil', NULL, NULL, FALSE, 'Desenvolvimento de relatórios no Excel usando ferramentas de SSBI (Power Query, Power Pivot e Power View). Automatização de tarefas manuais usando programação VBA', 'Excel;Power BI;VBA;SQL;Power Query;Power Pivot;Power View', TRUE);