name: Release

on:
  push:
    branches: [ "main" ]

permissions:
  contents: write

jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    environment: Production

    steps:
    - uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'

    - name: Install Poetry
      uses: snok/install-poetry@v1
      with:
        version: 1.8.4
        virtualenvs-create: true
        virtualenvs-in-project: true

    - name: Install dependencies
      run: |
        poetry install --no-interaction

    - name: Extract version
      id: extract_version
      run: |
        VERSION=$(poetry version -s)
        echo "version=$VERSION" >> $GITHUB_OUTPUT
        echo "Versão encontrada: $VERSION"

    - name: Create GitHub Release
      uses: softprops/action-gh-release@v1
      with:
        tag_name: v${{ steps.extract_version.outputs.version }}
        name: Release v${{ steps.extract_version.outputs.version }}
        draft: false
        prerelease: false

      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}