name: Release

on:
  push:
    branches: [ "main" ]

permissions:
  contents: write

jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    environment: Production

    steps:
    - uses: actions/checkout@v3

    - name: Get latest release version
      id: get_version
      run: |
        LATEST_TAG=$(git describe --tags --abbrev=0 2>/dev/null || echo "v0.0.0")
        VERSION=${LATEST_TAG#v}
        IFS='.' read -r MAJOR MINOR PATCH <<< "$VERSION"
        NEW_PATCH=$((PATCH + 1))
        NEW_VERSION="$MAJOR.$MINOR.$NEW_PATCH"
        echo "version=$NEW_VERSION" >> $GITHUB_OUTPUT
        echo "Versão anterior: $VERSION"
        echo "Nova versão: $NEW_VERSION"

    - name: Create GitHub Release
      uses: softprops/action-gh-release@v1
      with:
        tag_name: v${{ steps.get_version.outputs.version }}
        name: Release v${{ steps.get_version.outputs.version }}
        draft: false
        prerelease: false

      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}